from typing import Dict, Tuple
from .world import Graph, build_world, neighbors
from .actors import Actor, Player, Stats, ChaseBehavior, WaitBehavior

def init_game(seed: int = 7) -> Tuple[Graph, Dict[str,Actor], str, str]: ...
def legal_moves(graph: Graph, room: str) -> list[str]: ...
def apply_action(action: dict, graph: Graph, actors: Dict[str,Actor]) -> None: ...

def loop() -> None: ...
if __name__ == "__main__":
    loop()
