from collections import deque
from typing import Dict, List

Graph = Dict[str, List[str]]

def build_world(n_rooms: int, seed: int) -> Graph: ...
def neighbors(graph: Graph, room: str) -> List[str]: ...
def shortest_path(graph: Graph, src: str, dst: str) -> List[str]: ...
def is_connected(graph: Graph, start: str) -> bool: ...
